### ISSUE TITLE
image-maxsize-webpack-loader

### ISSUE THREAD

**Issue by danielberndt** [Levelmoney/resize-image-loader#1]
Hey!

have you seen https://github.com/shekhei/image-maxsize-webpack-loader by @shekhei ?

While there certainly are differences between the two approaches, they both are operating in the same space. So maybe it's worth collaborating and eventually merging.

Cheers!

**Comment by shekhei** [comment]
what a coincidence! Rather interesting approach! I am wondering though, how would this approach work in css files?

**Comment by puppybits** [comment]
I didn't see image-maxsize. I was looking at the webpack-image-loader with does minification/optimization. 

The media queries in CSS i think you still have to handle screen size and pixel density separately (-webkit-min-device-pixel-ratio). That makes it a little more complex. I guess it could be coupled with a sass mix-in to generate it for you. The image-maxsize-loader is a good solution for CSS but the srcSet is recommended more.

The srcSet is very straight forward. It handles pixel density and screen size together so you don't get hit by another network call. Here's a couple resources the talking points for srcSet: http://bradfrost.com/blog/post/responsive-images/ https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

**Comment by danielberndt** [comment]
using the image-maxsize-webpack-loader srcSet can be applied like this:

```
<img 
  width="80"
  src={require("./images/logo.png?max-width=80")} 
  srcset={`${require("./images/logo.png?max-width=80")} 1x, ${require("./images/logo.png;?max-width=160")} 2x`} 
  alt="logo">
```

it's not as succinct as your solution, but I guess this sort of code will usually be abstracted away anyway.

**Comment by shekhei** [comment]
@puppetbit yeah using my solution does have its flaws when it comes to srcSet, not exactly the cleanest. Would it be beneficial to like perhaps create a helper to generate all the "defined" sizes?

**Comment by puppybits** [comment]
What do you mean by defined sizes? Usually developers targeting a few screen size break points but that doesn't always correlate to images sizes (unless all images are are full width on all screens). As much as I don't like putting webpack specific code in the JS files I couldn't think of another way. 

Would a helper either return rebuilt media queries or the srcSet? The css media query option does have the benefit of being about to support a wider range of browsers than srcSet. I assume if the default image is the desktop 1x size then recent iPhones and androids will work with srcSet. 

Is there a clean way to generate media queries to support old gingerbread and iOS 5 devices?

**Comment by shekhei** [comment]
Well, what I mean would be something like,
```css
/*in the css*/
url(image-size?max-width=80w!./image.jpg);
url(image-size?max-width=200w!./image.jpg);
```

```html
<!-- in the html -->
<img srcSet="{image-size?set!./image.jpg}" src="{image-size?max-width=80w!./image.jpg)}"/>
```

and the set would result in a set of the "created" resized-images? I havnt touched the webpack things for a while, I cant remember if we can use promises for this, if we can, we can easily generate the set after the whole compilation, and we get the benefits of both worlds, and cached.

**Comment by puppybits** [comment]
Looking into the media query that would have to be written it would be a little complex (and more prone to breakage). For just one image it's something like this:

    /* older iphones */
    @media only screen and (max-width: 320px) 
      .myImage 
        background: url('img-320w.png')

    /* W3C stadard*/
    @media only screen and (min-resolution:96dpi) and (max-width: 320px) 
      .myImage 
        background: url('img-640w.png')

    /* retina iPhones */
    @media only screen and (-webkit-device-pixel-ratio:2) and (max-width: 320px) 
      .myImage 
        background: url('img-640w.png')

    @media only screen and (-webkit-device-pixel-ratio:3) and (max-width: 320px) 
      .myImage 
        background: url('img-960w.png')

Also users may want sass, scss, less, style or other css transpiler. It seems like this make more sense to build as a sass/less mixin where you can manually pass in the image sizes you are stepping up to. That would also make it available to the rest of the development community that isn't using webpack.
