### ISSUE TITLE
webpack-dev-server crash

### ISSUE THREAD

**Issue by onpaws** [Levelmoney/resize-image-loader#11]
Hey,
thanks for your work on making what looks like a nice loader.

I'm having a spot of trouble getting started. When I include an image with a standard require like so:
`let a = require('./assets/_@1x.jpg');`
things work as expected. 

Yet for some reason, 
`let b = require('resize-image?sizes[]=200w,sizes[]=900w!./assets/_@1x.jpg');`
crashes my webpack dev server.

I'm using the following flags:
`webpack-dev-server --content-base build --devtool #eval-source-map --progress --colors --hot --inline`

I wish I could say the [log](https://github.com/Levelmoney/resize-image-loader/files/205567/npm-debug.txt) were more helpful.

Just wanted to check if anyone else is having this problem before diving deep into this. 
Suggestions most welcome! This is a React project (0.14.7). Mac OS X 10.11.4. Chrome Canary.

[webpack.config.js.txt](https://github.com/Levelmoney/resize-image-loader/files/205568/webpack.config.js.txt)

**Comment by puppybits** [comment]
Did you install image magick? 

Also I added debug support. Prefix the command line call with DEBUG=resize-image-loader. That should give some more details about what's going on. 

- bobby

**Comment by onpaws** [comment]
Sweet. ImageMagick was the culprit, thanks! 
TL, DR: I generally use GraphicsMagick and made a super simple change so we default to `gm`.

---
Because I already had GraphicsMagick installed, when I saw this [require](https://github.com/Levelmoney/resize-image-loader/blob/master/index.js#L14), I jumped the gun a bit based on these [docs](http://www.graphicsmagick.org/FAQ.html#how-does-graphicsmagick-differ-from-imagemagick) assuming GraphicsMagick would work. And it does, when you `require()` it properly (i.e. remove `.subClass({imageMagick: true});`). 
It would be cool to simply log out missing dependencies, i.e. without a crash.

Heads up: apparently `gm` didn't used to support WebP but now it seems like it [might](http://www.graphicsmagick.org/NEWS.html).
While WebP is not required for my project it looks like @puppybits had a [need](https://github.com/Levelmoney/resize-image-loader/pull/4#issuecomment-147771537). 

There appears to be a backstory here with the [licensing](
http://www.graphicsmagick.org/FAQ.html#how-often-does-graphicsmagick-pick-up-new-code-from-imagemagick), but just in case anyone like me just wants to stick with GraphicsMagick:
[fork](/onpaws/resize-image-loader), [PR](https://github.com/Levelmoney/resize-image-loader/pull/12)

**Comment by onpaws** [comment]
Thanks Bobby! Interesting ideas at play here.
