### ISSUE TITLE
support other loaders

### ISSUE THREAD

**Issue by Coobaha** [Levelmoney/resize-image-loader#3]
according to this lines https://github.com/Levelmoney/resize-image-loader/blob/master/index.js#L53-L54 - all other loaders are ignored, so we cannot use preconfigured loaders for example to add file-loader urls or minify every image.

**Comment by puppybits** [comment]
I'll look into it. The GM library is minifying it's output but that doesn't mean their aren't better optimizers out there.

**Comment by puppybits** [comment]
There's not a way that I found to pass along a binary with the multiple image as well as output the files for the user's app to access. 

```javascript
var myImage = require('assets/images/my-image.png'); // can be chained with file-loader, url-loader or minify-loader to either get a link to the resource or a datauri
var multipleImages = require('resize-image?sizes[]=400&sizes[]=200?assets/images/my-image.png'); // needs to return access to multiple images. The current output is a string that can be fed into the srcSet attribute in an image.
```

Is there an output format that is more versatile and would allow for chaining or be simpler for developers to use?
